SELECT DISTINCT failure_reason FROM experiment_error_summary
UNION
SELECT DISTINCT failure_reason FROM experiment_completed_summary
UNION
SELECT DISTINCT failure_reason FROM experiment_attention_summary


-- OutOfMemoryError: CUDA out of memory. Tried to allocate 1.04 GiB. GPU 0 has a total capacity of 15.47 GiB of which 496.12 MiB is free. Including non-PyTorch memory, this process has 13.36 GiB memory in use. Of the allocated memory 10.74 GiB is allocated by PyTorch, and 2.29 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
-- OutOfMemoryError: CUDA out of memory. Tried to allocate 220.00 MiB. GPU 0 has a total capacity of 15.47 GiB of which 122.00 MiB is free. Including non-PyTorch memory, this process has 13.99 GiB memory in use. Of the allocated memory 13.35 GiB is allocated by PyTorch, and 319.11 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
-- OutOfMemoryError: CUDA out of memory. Tried to allocate 4.49 GiB. GPU 0 has a total capacity of 15.47 GiB of which 240.31 MiB is free. Including non-PyTorch memory, this process has 13.99 GiB memory in use. Of the allocated memory 11.85 GiB is allocated by PyTorch, and 1.81 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
-- OutOfMemoryError: CUDA out of memory. Tried to allocate 510.00 MiB. GPU 0 has a total capacity of 15.47 GiB of which 498.12 MiB is free. Including non-PyTorch memory, this process has 13.35 GiB memory in use. Of the allocated memory 12.32 GiB is allocated by PyTorch, and 723.40 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
-- OutOfMemoryError: CUDA out of memory. Tried to allocate 510.00 MiB. GPU 0 has a total capacity of 15.47 GiB of which 500.12 MiB is free. Including non-PyTorch memory, this process has 13.35 GiB memory in use. Of the allocated memory 12.34 GiB is allocated by PyTorch, and 700.20 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
